# Assignment: Data Wrangling
## `! git clone https://github.com/DS3001/wrangling`
## Do Q2, and one of Q1 or Q3.

In [23]:
! git clone https://github.com/DS3001/wrangling

Cloning into 'wrangling'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 92 (delta 42), reused 18 (delta 18), pack-reused 40 (from 1)
Receiving objects: 100% (92/92), 18.08 MiB | 7.53 MiB/s, done.
Resolving deltas: 100% (43/43), done.

**Q1.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?

      * The paper is about a new framework data tidying that makes data cleaning

more efficient and better prepares data for analysis.

  2. Read the introduction. What is the "tidy data standard" intended to accomplish?

      * The tidy data standard is intended to reduce the amount of time spent cleaning data and facilitate data exploration and analysis.

  3a. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way."

      * The sentence means that every dataset has an underlining structure(columns and rows), however, what they contain, what they are about, and the meaning/context behind their messiness varies.
  
  3b. What does this sentence mean: "For a given dataset, itâ€™s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."

      * The sentence means that when given a dataset, it is easy to see what values belong to what variable and observation. For example, I have a dataset with age(v) and observation(Sarah). The value for Sarah's age is 17. This is easy to define. However, without an example or dataset to base the definition of variable and observation on, the two terms in themselves can be hard to explain.

  4. Read Section 2.2. How does Wickham define values, variables, and observations?

      * Wickham defines values as numbers and string, and variables and observations as a way to organize values. Variables have the same attribute across units. Observations have the same unit across attributes.

  5. How is "Tidy Data" defined in section 2.3?

      * Tidy Data is defined as having a variable forms a column, an observation-- a row-- and observational unit--a table.

  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?

      * The five most common problems in messy datasets are column headers as values, multiple variables stored in the same column, variables stored in both rows and columns, multiple types in one table, and one type in multiple tables.

  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?

      * The element variable has two variable types stored under it: tmax and tmin. Table 11 is messy because of this, and table 12 is tidy and molten because duplication of observations that occur as a result of element having two variable types has been resolved. The molten data is then made tidy when the two variable types become two distinct columns.

  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?

      * The chicken and egg problem with focusing on tidy data is that if a data is only as good as the tools used to clean it then the quality of data will be linked to the quality of the tools that work on it. Wickham hopes others will develop on the tidy data framework by developing better tools for tidying.

**Q2.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the `./data/sharks.csv` data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.
3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [24]:
cd /content/wrangling/assignment

/content/wrangling/assignment

In [25]:
## AirBnB Dataset Wrangling
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

air= pd.read_csv('./data/airbnb_hw.csv')
print(air.shape)
print(air.dtypes)

air['Price']= air['Price'].str.replace(',', '')
print(air['Price'].unique())

air['Price']= pd.to_numeric(air['Price'],  errors= 'coerce')
print(air['Price'].dtypes)
print(air['Price'].unique())

print( 'Total missing: ', sum(air['Price'].isnull() ) )

(30478, 13)
Host Id                         int64
Host Since                     object
Name                           object
Neighbourhood                  object
Property Type                  object
Review Scores Rating (bin)    float64
Room Type                      object
Zipcode                       float64
Beds                          float64
Number of Records               int64
Number Of Reviews               int64
Price                          object
Review Scores Rating          float64
dtype: object
['145' '37' '28' '199' '549' '149' '250' '90' '270' '290' '170' '59' '49'
 '68' '285' '75' '100' '150' '700' '125' '175' '40' '89' '95' '99' '499'
 '120' '79' '110' '180' '143' '230' '350' '135' '85' '60' '70' '55' '44'
 '200' '165' '115' '74' '84' '129' '50' '185' '80' '190' '140' '45' '65'
 '225' '600' '109' '1990' '73' '240' '72' '105' '155' '160' '42' '132'
 '117' '295' '280' '159' '107' '69' '239' '220' '399' '130' '375' '585'
 '275' '139' '260' '35' '133' '300' '289' '179' '98' '195' '29' '27' '39'
 '249' '192' '142' '169' '1000' '131' '138' '113' '122' '329' '101' '475'
 '238' '272' '308' '126' '235' '315' '248' '128' '56' '207' '450' '215'
 '210' '385' '445' '136' '247' '118' '77' '76' '92' '198' '205' '299'
 '222' '245' '104' '153' '349' '114' '320' '292' '226' '420' '500' '325'
 '307' '78' '265' '108' '123' '189' '32' '58' '86' '219' '800' '335' '63'
 '229' '425' '67' '87' '1200' '158' '650' '234' '310' '695' '400' '166'
 '119' '62' '168' '340' '479' '43' '395' '144' '52' '47' '529' '187' '209'
 '233' '82' '269' '163' '172' '305' '156' '550' '435' '137' '124' '48'
 '279' '330' '5000' '134' '378' '97' '277' '64' '193' '147' '186' '264'
 '30' '3000' '112' '94' '379' '57' '415' '236' '410' '214' '88' '66' '71'
 '171' '157' '545' '1500' '83' '96' '1800' '81' '188' '380' '255' '505'
 '54' '33' '174' '93' '740' '640' '1300' '440' '599' '357' '1239' '495'
 '127' '5999' '178' '348' '152' '242' '183' '253' '750' '259' '365' '273'
 '197' '397' '103' '389' '355' '559' '38' '203' '999' '141' '162' '333'
 '698' '46' '360' '895' '10' '41' '206' '281' '449' '388' '212' '102'
 '201' '2750' '4750' '432' '675' '167' '390' '298' '339' '194' '302' '211'
 '595' '191' '53' '361' '480' '8000' '4500' '459' '997' '345' '216' '218'
 '111' '735' '276' '91' '490' '850' '398' '36' '775' '267' '625' '336'
 '2500' '176' '725' '3750' '469' '106' '460' '287' '575' '227' '263' '25'
 '228' '208' '177' '880' '148' '116' '685' '470' '217' '164' '61' '645'
 '699' '405' '252' '319' '268' '419' '343' '525' '311' '840' '154' '294'
 '950' '409' '184' '257' '204' '241' '2000' '412' '121' '288' '196' '900'
 '647' '524' '1750' '309' '510' '1495' '1700' '799' '383' '372' '492'
 '327' '1999' '656' '224' '173' '875' '1170' '795' '690' '146' '465'
 '1100' '151' '274' '429' '825' '282' '256' '1111' '620' '271' '161' '51'
 '855' '579' '1174' '430' '20' '899' '649' '485' '181' '455' '4000' '243'
 '342' '590' '560' '374' '437' '232' '359' '985' '31' '244' '254' '723'
 '237' '428' '370' '34' '1400' '580' '2520' '221' '749' '1600' '2695'
 '306' '202' '680' '570' '520' '223' '2295' '213' '1065' '346' '24' '286'
 '296' '266' '26' '995' '1368' '393' '182' '635' '258' '780' '589' '347'
 '1250' '1350' '446' '3200' '1050' '1650' '1550' '975' '323' '6500' '2499'
 '1850' '2250' '715' '461' '540' '356' '439' '384' '569' '1900' '22' '785'
 '626' '830' '318' '444' '321' '401' '1499' '888' '369' '770' '386' '366'
 '344' '630' '313' '597' '262' '509' '10000' '278' '312' '789' '1195'
 '422' '21' '765' '3500' '945' '326' '3100' '2486' '3390' '1356' '2599'
 '472' '454' '328' '396' '291']
int64
[  145    37    28   199   549   149   250    90   270   290   170    59
    49    68   285    75   100   150   700   125   175    40    89    95
    99   499   120    79   110   180   143   230   350   135    85    60
    70    55    44   200   165   115    74    84   129    50   185    80
   190   140    45    65   225   600   109  1990    73   240    72   105
   155   160    42   132   117   295   280   159   107    69   239   220
   399   130   375   585   275   139   260    35   133   300   289   179
    98   195    29    27    39   249   192   142   169  1000   131   138
   113   122   329   101   475   238   272   308   126   235   315   248
   128    56   207   450   215   210   385   445   136   247   118    77
    76    92   198   205   299   222   245   104   153   349   114   320
   292   226   420   500   325   307    78   265   108   123   189    32
    58    86   219   800   335    63   229   425    67    87  1200   158
   650   234   310   695   400   166   119    62   168   340   479    43
   395   144    52    47   529   187   209   233    82   269   163   172
   305   156   550   435   137   124    48   279   330  5000   134   378
    97   277    64   193   147   186   264    30  3000   112    94   379
    57   415   236   410   214    88    66    71   171   157   545  1500
    83    96  1800    81   188   380   255   505    54    33   174    93
   740   640  1300   440   599   357  1239   495   127  5999   178   348
   152   242   183   253   750   259   365   273   197   397   103   389
   355   559    38   203   999   141   162   333   698    46   360   895
    10    41   206   281   449   388   212   102   201  2750  4750   432
   675   167   390   298   339   194   302   211   595   191    53   361
   480  8000  4500   459   997   345   216   218   111   735   276    91
   490   850   398    36   775   267   625   336  2500   176   725  3750
   469   106   460   287   575   227   263    25   228   208   177   880
   148   116   685   470   217   164    61   645   699   405   252   319
   268   419   343   525   311   840   154   294   950   409   184   257
   204   241  2000   412   121   288   196   900   647   524  1750   309
   510  1495  1700   799   383   372   492   327  1999   656   224   173
   875  1170   795   690   146   465  1100   151   274   429   825   282
   256  1111   620   271   161    51   855   579  1174   430    20   899
   649   485   181   455  4000   243   342   590   560   374   437   232
   359   985    31   244   254   723   237   428   370    34  1400   580
  2520   221   749  1600  2695   306   202   680   570   520   223  2295
   213  1065   346    24   286   296   266    26   995  1368   393   182
   635   258   780   589   347  1250  1350   446  3200  1050  1650  1550
   975   323  6500  2499  1850  2250   715   461   540   356   439   384
   569  1900    22   785   626   830   318   444   321   401  1499   888
   369   770   386   366   344   630   313   597   262   509 10000   278
   312   789  1195   422    21   765  3500   945   326  3100  2486  3390
  1356  2599   472   454   328   396   291]
Total missing:  0

In [26]:
## Shark Data Wrangling

sharks= pd.read_csv('./data/sharks.csv', low_memory= False)
sharks['Type'].unique()
## Unprovoked and Provoked seem distinct enough, they will be left alone. Unconfirmed + Unverified+ Under investigation + Questionable + Invalid seem to belong together as they
# suggest there is some evidence that has not yet been explored, Sea Disaster+Boating+Boat+Boatomg+Watercraft seem to fit in the same category of happening on the water. Nan is
# missing. The observations that have values that suggest evidence will be coded as 'Unknown' because there is still some knowledge there and it is not missing

sharks['Type'] = sharks['Type'].replace(['Sea Disaster', 'Boat','Boating','Boatomg'],'Watercraft')
sharks['Type'] = sharks['Type'].replace(['Unconfirmed', 'Unverified','Under investigation','Questionable','Invalid'],'Unknown')
sharks['Type'].unique()

array(['Unprovoked', 'Provoked', 'Unknown', 'Watercraft', nan],
      dtype=object)

In [27]:
sharks

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,0,2020.02.05,05-Feb-2020,2020.0,Unprovoked,USA,Maui,NaN,Stand-Up Paddle boarding,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020.01.30.R,Reported 30-Jan-2020,2020.0,Provoked,BAHAMAS,Exumas,NaN,Floating,Ana Bruna Avila,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020.01.17,17-Jan-2020,2020.0,Unprovoked,AUSTRALIA,New South Wales,Windang Beach,Surfing,Will Schroeter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020.01.16,16-Jan-2020,2020.0,Unprovoked,NEW ZEALAND,Southland,Oreti Beach,Surfing,Jordan King,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020.01.13,13-Jan-2020,2020.0,Unprovoked,USA,North Carolina,"Rodanthe, Dare County",Surfing,Samuel Horne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6457,6457,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6458,6458,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6459,6459,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6460,6460,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6461,6461,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
!pwd

/content/wrangling/assignment

In [29]:
cd ../

/content/wrangling

In [30]:
cd ./data/

/content/wrangling/data

In [31]:
ls -al

total 12028
drwxr-xr-x 2 root root    4096 Sep 21 18:22 ./
drwxr-xr-x 7 root root    4096 Sep 21 18:30 ../
-rw-r--r-- 1 root root 7181667 Sep 21 18:22 justice_data.parquet
-rw-r--r-- 1 root root 3538329 Sep 21 18:22 sharks.csv
-rw-r--r-- 1 root root 1582160 Sep 21 18:22 VirginiaPretrialData2017Codebook.pdf

In [32]:
## Justice Data Wrangling

df= pd.read_parquet('justice_data.parquet')

df.columns.tolist()
df.loc[:, 'WhetherDefendantWasReleasedPretrial']
df['WhetherDefendantWasReleasedPretrial'].unique()
df['WhetherDefendantWasReleasedPretrial'].value_counts()
df['WhetherDefendantWasReleasedPretrial']= df['WhetherDefendantWasReleasedPretrial'].replace(9,np.nan)
df['WhetherDefendantWasReleasedPretrial'].unique()
df['WhetherDefendantWasReleasedPretrial'].value_counts()

WhetherDefendantWasReleasedPretrial
1.0    19154
0.0     3801
Name: count, dtype: int64

In [33]:
pwd

'/content/wrangling/data'

In [34]:
cd ../

/content/wrangling

In [39]:
# Pretrial Data Wrangling

ptd= pd.read_csv('pretrial_data.csv')
ptd['ImposedSentenceAllChargeInContactEvent'].unique()
missing= ptd['ImposedSentenceAllChargeInContactEvent'].isna()

SType= ptd['SentenceTypeAllChargesAtConvictionInContactEvent']
SType.unique()

<ipython-input-39-33b50b58384b>:3: DtypeWarning: Columns (2,5,6,8,80,81,82,83,84,85,109,164,165,166,167,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,271,272,273,274,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,302,303,304,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,707) have mixed types. Specify dtype option on import or set low_memory=False.
  ptd= pd.read_csv('pretrial_data.csv')

0        False
1        False
2        False
3        False
4        False
         ...
22981    False
22982    False
22983    False
22984    False
22985    False
Name: ImposedSentenceAllChargeInContactEvent, Length: 22986, dtype: bool

array([9, 0, 1, 4, 2])

In [21]:
print( pd.crosstab(missing, SType), '\n') # Category 4 is cases where the charges were dismissed

missing = missing.mask( SType == 4, 0) # Replace length with 0 when type ==4
missing = missing.mask( SType == 9, np.nan) # Replace length with np.nan when type == 9

missing_NA = missing.isnull() # Create a new missing dummy
print( pd.crosstab(missing_NA, SType), '\n')
print( np.sum(missing_NA),'\n') # 274 missing, much better

df['ImposedSentenceAllChargeInContactEvent'] = missing

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

274

**Q3.** Many important datasets contain a race variable, typically limited to a handful of values often including Black, White, Asian, Latino, and Indigenous. This question looks at data gathering efforts on this variable by the U.S. Federal government.

1. How did the most recent US Census gather data on race?
    * The US Census gathers race data using self-identification on the Census survey.

2. Why do we gather these data? What role do these kinds of data play in politics and society? Why does data quality matter?
    * Race plays a huge rule in politics and society. Gathering data on race can help in understanding or better perceiving and addressing inequalities between races. Data quality matters because if these inequalities or issues are to be addressed appropriately, the data must reflect reality.

3. Please provide a constructive criticism of how the Census was conducted: What was done well? What do you think was missing? How should future large scale surveys be adjusted to best reflect the diversity of the population? Could some of the Census' good practices be adopted more widely to gather richer and more useful data?
    * Because the  Census collects data on a lot of people, the methodology/ the fact that it is a survey makes sense. Surveys can reach a lot of people faster and you can get results more easily. However, a survey only works if participants are willing to answer the questions on them, and answer them truthfully. This means that while a survey is a great way for obtaining large scale data, it is not the best as non-response is frequent and some participants can 'lie' or misinterpret survey questions or present false information if they are self-identifying or self-reporting. These issues can be addressed by framing questions more clearly, providing surveys in multiple languages, and providing more options that represent diveristy so people respond more appropraitely. These adjustments to the census survey can help analyze certain nuances in data and in the groups they represent.

4. How did the Census gather data on sex and gender? Please provide a similar constructive criticism of their practices.
    * The Census asked respondents to report identify only as either Female or Male. This limitation especially when it comes to gender will make our data unrepresentative as the diversity of gender is not represented.

5. When it comes to cleaning data, what concerns do you have about protected characteristics like sex, gender, sexual identity, or race? What challenges can you imagine arising when there are missing values? What good or bad practices might people adopt, and why?

    * When it comes to cleaning data, protected characteristics are most likely to be missing so it is important to explore the pattern of missingness. When there are missing values, it is important to examine why the data might be missing so you know how better to handle it, otherwise you stand missing a lot of insight from data, by removing or excluding missing data. Sometimes, removing data is appropriate for the missingness pattern, sometime imputing data is appropriate. However, it is difficult to determine what values to impute especially for categorical variables.

6. Suppose someone invented an algorithm to impute values for protected characteristics like race, gender, sex, or sexuality. What kinds of concerns would you have?

      * If someone built an algorithm that imputed values for protected characteristics, I would be curious about how the algorithm was built. What data was used to inform it about what values to impute, and is the data representative or skewed in favor of majority groups. For instance, how likely is the algorithm to impute heterosexual because it has high frequency? What metrics are being used to determine that the imputation is something other than heterosexual?